### PR TITLE
Feature/modular callform

### PR DESCRIPTION
**Pull request by sirpengi**
Implement the old feature https://github.com/fightforthefuture/battleforthenet/pull/49 in v2 of site.

tagging @fightforthefuture/battle-for-the-net for additional code review

### CODE REVIEW

**Comment by sirpengi** [comment]
I would make the template more modular, the infrastructure is already there to make that super easy to accomplish.

**Comment by mikemorris** [comment]
Just for clarity, it looks like this would preserve the existing functionality as default (and set the home page to display the call form) for `?call=1`, and add support for the daily call campaign (and potentially others) via `?campaign=daily`, right?

Does this support the petition form initial flow, with daily call campaign after-action when passing just `?campaign=daily` (not necessary, but could be useful)?

**Comment by jlev** [comment]
Should the disclaimer and other adjustable text be in the props interface, or the campaign const? At least for the daily calls page, we need to be able to tell users that their phone number may be used repeatedly.

`<p className="disclaimer">Your phone number will only be used for Battle for the Net to connect you with Congress and the FCC. <a href="/privacy" target="_blank">Privacy Policy</a></p>`

**Comment by sirpengi** [comment]
@mikemorris yes, the link I provided only had the `call` flag to make it more direct to review.  The `campaign` flag affects both call forms, whether it's directly shown, or part of the petition flow.

@jlev it should be part of the campaign const, to be injected in the render function.

**Comment by jlev** [comment]
Thanks @sirpengi! Appreciate the work. I'm good to merge when you all are.

**Comment by jlev** [comment]
When I hit https://www.battleforthenet.com/?call=daily I still get the disclaimer "Your phone number will only be used to make this call". Is that the right URL switch to enable this new rendering?

**Comment by mikemorris** [comment]
@jlev It should be https://www.battleforthenet.com/?call=1&campaign=daily now (which is showing me the correct disclaimer)

**Pull request merged**
