### PR TITLE
Dp day of action

### PR DESCRIPTION
**Pull request by tibetsprague**

### CODE REVIEW

**Comment by mikemorris** [comment]
Had been noticing these errors in Sentry, thanks for hitting this!

**Comment by tibetsprague** [comment]
they still seem to be happening though....

**Comment by mikemorris** [comment]
@tibetsprague Errors in Sentry are pointing to https://github.com/fightforthefuture/battleforthenet/blob/ee64d4a1f1eea17f597d6d8345c91b7ccc4e21a4/july12/index.html#L346-L349, which would happen before `battle.js` is even loaded, maybe move that bit into https://github.com/fightforthefuture/battleforthenet/blob/gh-pages/_src/js/index.js until we can get this page refactored onto the new structure?

**Comment by tibetsprague** [comment]
@mikemorris I'm back on the grid, looks like you took care of it?

**Comment by mikemorris** [comment]
Yea, think I was able to fix it with https://github.com/fightforthefuture/battleforthenet/commit/27e15ef5edb54cae1846a7bb63a58053da170f6d @tibetsprague

**Pull request merged**
